### ISSUE TITLE
SteamClient.doLogin() issue

### ISSUE THREAD

**Issue by n4bz0r** [SteamRE/SteamKit#105]
Hello. I'm using java(android) fork of SteamKit https://github.com/aegamesi/SteamKit-Java. I know it's not exactly correct place to post the issue, but you might give me an idea how to work this out. I described my problem on fork git: https://github.com/Top-Cat/SteamKit-Java/issues/8, but no help there.

Additionally to my previous post here is what happens in log (I worked out null pointer and added raw message log string):
```java
03-13 18:58:44.709    1260-1272/com.n4bz0r.steamtradebot I/TcpConnection﹕ Connecting to [72.165.61.187:27017]...
03-13 18:58:44.985    1260-1272/com.n4bz0r.steamtradebot I/TcpConnection﹕ Connected!
03-13 18:58:44.985    1260-1272/com.n4bz0r.steamtradebot I/Bot #0﹕ Bot started
03-13 18:58:45.257    1260-1274/com.n4bz0r.steamtradebot I/CMClient﹕ Raw message: 1303
03-13 18:58:45.257    1260-1274/com.n4bz0r.steamtradebot I/CMClient﹕ <- Recv'd EMsg: ChannelEncryptRequest (1303) (Proto: false)
03-13 18:58:45.257    1260-1274/com.n4bz0r.steamtradebot I/CMClient﹕ Got encryption request. Universe: Public Protocol ver: 1
03-13 18:58:45.317    1260-1274/com.n4bz0r.steamtradebot I/CMClient﹕ Sent -> EMsg: ChannelEncryptResponse (Proto: false)
03-13 18:58:45.933    1260-1274/com.n4bz0r.steamtradebot I/CMClient﹕ Raw message: 1305
03-13 18:58:45.933    1260-1274/com.n4bz0r.steamtradebot I/CMClient﹕ <- Recv'd EMsg: ChannelEncryptResult (1305) (Proto: false)
03-13 18:58:45.989    1260-1272/com.n4bz0r.steamtradebot I/Bot #0﹕ Connected. Trying to log on
03-13 18:58:46.005    1260-1272/com.n4bz0r.steamtradebot I/CMClient﹕ Sent -> EMsg: ClientLogon (Proto: true)
...
Here goes ~30 seconds (timeout like) delay
...
03-13 18:59:51.557    1260-1274/com.n4bz0r.steamtradebot I/CMClient﹕ Raw message: -84405297
03-13 18:59:51.557    1260-1274/com.n4bz0r.steamtradebot I/NEW_EX﹕ Exception: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either than the input has been truncated or that an embedded message misreported its own length.
03-13 18:59:51.557    1260-1274/com.n4bz0r.steamtradebot I/CMClient﹕ <- Recv'd EMsg: Invalid (0) (Proto: true)
```

Why do I get such a weird message (-84405297) from server? I'll provide as much info as needed. Just don't know from where to start.

**Comment by Netshroud** [comment]
You're correct, we don't - and can't - provide direct support for third-party ports. Especially forks of ports.

What I do know however, is that if you don't send a valid logon message within about 30s, the Steam servers will kick you off with a failed logon (non-proto) message as seen in [CMClient](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/CMClient.cs#L419) and [SteamUser](https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/SteamKit2/Steam/Handlers/SteamUser/SteamUser.cs#L439).

The `EMsg` you got (-84405297) would be protobuf message 2063078351, which is way out of range.

Since your `EMsg` makes no sense, and your log says that you sent a ClientLogon message, the most likely sequence of events is:

1. You connect to Steam.
2. You receive a `ChannelEncryptRequest` message.
3. You parse the `ChannelEncryptRequest` message and construct a `ChannelEncryptResponse` message.
4. You send a `ChannelResponseMessage`.
5. You receive a `ChannelEncryptResult` message.
6. You parse the `ChannelEncryptResult` message and construct a ClientLogon message.
7. You send an invalid `ClientLogon` message. It's valid enough not to trigger an outright disconnection, but invalid enough that the server ignores it.
8. The Steam server, having not received a valid logon message, sends you a non-protobuf `ClientLogonResponse` message and disconnects you.
9. You incorrectly parse the `ClientLogonResponse` message, leading to a client crash.

The fault probably lies in one or more of the following areas:

1. Message encryption
2. Message serialisation
3. Message deserialisation

**Comment by n4bz0r** [comment]
Thanks a lot for your answer. I'll try to work this out in this direction.
