### ISSUE TITLE
When records num >999,NetHookAnalyzer2 don't show them by sequence

### ISSUE THREAD

**Issue by sy1989** [SteamRE/SteamKit#109]

**Comment by sy1989** [comment]
1000 is afer of 99 and so on.

**Comment by Netshroud** [comment]
It works for me. I have some missing numbers due to Steam Pipe chunks counting towards the sequence number, but I see, in order:
1
5
19
23
33
37
38
39
40
41
42
43
44
45
46
47
48
49
51
1478
1479
1481
etc.

Can you provide a screenshot, and ideally a sample data set (delete any dumped messages containing sensitive data)?

**Comment by sy1989** [comment]
![111](https://cloud.githubusercontent.com/assets/5002924/7366505/5fe3b2ba-edcb-11e4-9248-8ddcd3424f32.png)
i think you missed set ListViewItemSorter while the orginal NetHookAnalyzer set it

**Comment by sy1989** [comment]
The sequence we get from EnumerateFiles is not like what we have seen in explorer.
Maybe we can change it to "directoryInfo.EnumerateFiles("*.bin", SearchOption.TopDirectoryOnly).OrderBy(f =>f.LastWriteTimeUtc)" or set ListViewItemSorter like what the orginal NetHookAnalyzer do.
