### ISSUE TITLE
[Bug]: Fail to generate SteamLanguage code with ObjCInterfaceGen

### ISSUE THREAD

**Issue by ValvojaX** [SteamRE/SteamKit#1092]
### What did you expect to happen?

Expected to generate SteamLanguage.h and SteamLanguageInternal.h with ObjCInterfaceGen

### Instead of that, what actually happened?

Received unhandled exception error

### Which operating system are you running on?

Windows

### Which .NET Runtime are you running on?

.NET Core or .NET 5 or higher.

### Version

6.0

### Relevant log output

```shell
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int64.Parse(String s)
   at SteamLanguageParser.ObjCInterfaceGen.EmitEnumNode(EnumNode enode, StringBuilder sb, Int32 level) in D:\SteamKit-master\Resources\SteamLanguageParser\Generator\ObjCInterfaceGen.cs:line 113
```

### Example Code

```csharp
Uncomment line from Program.cs to generate code for ObjCInterfaceGen. Run generate.bat in SteamLanguage
```

**Comment by yaakov-h** [comment]
Thanks for the bug report.

This code is left over from a very old project of mine to port SteamKit to Objective-C so that I could get Steam chat on iOS. This predates Steam's own app, and Swift, and I haven't touched it in many years.

Since it wasn't designed to be generally reusable, it relies on some boilerplate in [and old repo of mine](https://github.com/yaakov-h/CRBoilerplate) that similarly hasn't been touched in nearly a decade.

I've put up a Pull Request to fix the crash you encountered, but you still (most likely) won't be able to use this as-is.

If you want to make modifications to generate code that suits your purpose, or code that is more general-purpose, then feel free to do so.
