### ISSUE TITLE
Its possible to get users at current game?

### ISSUE THREAD

**Issue by mfandre** [SteamRE/SteamKit#111]
Its possible to get users at current game?

**Comment by Netshroud** [comment]
Would you care to re-word that?

**Comment by mfandre** [comment]
Imagine I entered in dota2 match, I want to get all users names and ids at current game. So I need to know if its possible with SteamKit or I need to use another tool.

**Comment by acidhax** [comment]
Any idea? Join a match - Get list of connected users, scores, etc?

**Comment by mfandre** [comment]
acidhax, 

Is it possible to hook sent messages? Do you have any code snippet to this?

**Comment by acidhax** [comment]
I don't, but I've seen mentions of "NetHook Steam". I think it can monitor all messages from the Game Coordinator.

**Comment by acidhax** [comment]
http://www.reddit.com/r/SteamBot/comments/2rt2fk/how_to_get_gift_notifications/

**Comment by VoiDeD** [comment]
SteamKit requires a standalone connection to Steam. If you're using the regular Steam client and launching Dota from there, you'll likely want to look into the Steamworks SDK.

**Comment by acidhax** [comment]
Does the Steamworks SDK allow you to plug into existing games? It seems like its just an SDK for implementing your own game communicator.

**Comment by VoiDeD** [comment]
Somewhat. Steam overlay is a separate consumer of the Steamworks SDK (although of a separate set of private interfaces known as IClient), and it's able to get a list of current users in the game it's rendering over.

You'll need to make use of the [open steamworks](https://github.com/SteamRE/open-steamworks) headers, as that's the only available project that has reverse engineered the IClient interfaces. There would be a significant learning curve and a lot of Steam domain knowledge to learn in order to actually get something working.
