### ISSUE TITLE
CMServerList should respect servers order

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#178]
When specifying a cellid, Steam returns servers that are ordered (geographically?) starting with closest at the top.

CMServerList should use that order when weighting servers.

**Comment by Netshroud** [comment]
Thinking aloud:

Perhaps scoring was the wrong approach, since the order is important. And ideally, we want to hit the closest server every time.

Another approach would be to have an ordered list of servers, with an unavailable flag that resets:
1. After a certain period of time
2. When the list is completely exhausted

Looking at Steamclient's implementation, it seems to roughly match the above. It has two lists that I can see:

* `CUtlVector<BadCMData_t>`
* `CUtlVector<netadr_t>`

In fact, the ordering is so important that Steam even has a `CCMInterface::ReorderCMsWithPreferredOrder` function.

I'll see if I can rejiggle this over the next few weeks.
