### ISSUE TITLE
How to receive a message from steam group.

### ISSUE THREAD

**Issue by cghippo** [SteamRE/SteamKit#242]
Sorry about another stupid question. How exactly would I have it receive a message from a group chat instead of doing callback.Message where it has to be in a pm? I got most things to work but this is another thing I'm having trouble with

**Comment by Netshroud** [comment]
> receive a message from a group chat instead of doing callback.Message where it has to be in a pm

What??

Please describe your issue concisely.

**Comment by cghippo** [comment]
Like, the issue is that callback.Message has to be a private message and cannot be in a steam chat.

**Comment by Netshroud** [comment]
Are you listening for a `FriendMsgCallback` or a `ChatMsgCallback`?

**Comment by cghippo** [comment]
yes

**Comment by Netshroud** [comment]
That was an English "or", not a programming "or".

If English isn't your first language, write in your native language and we may be able to find somebody who can translate better.

Otherwise, I'm going to close this. Come back when you can actually explain what you need help with.

Explain your setup. What you've achieved already. What you want to achieve. What you expecting to happen, and how that differs to what is actually happening. Some sample code, or a sample project, stripped of anything sensitive such as username/password/API key. Output from `DebugLog`. Any other context that may be useful (logged in at the same time on another computer / same computer / Steam is down for maintenance while this is happening / planets are aligned).

The fact that you're not even reading error messages (in your other issue) tells me a lot already. We're not here to serve you or do you work for you. We can help, but only if you put in enough effort that you can be helped.

**Comment by cghippo** [comment]
sorry
