### ISSUE TITLE
Unsigned library

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#249]
SteamKit2.dll library provided through nuget comes in unsigned version, which prohibits projects based on SK2 that would like to include signed assemblies.

```
Version=1.7.0.33680, Culture=neutral, PublicKeyToken=null'
```

Could you please consider **[signing the assembly with strong name](https://msdn.microsoft.com/en-us/library/xc31ft41(v=vs.110).aspx)**, so other projects based on SK2 could follow? Thank you.

**Comment by Netshroud** [comment]
Why?

**Comment by JustArchi** [comment]
Signing improves trustworthy, which is especially useful when it comes to AVs, which like to mark non-signed assemblies as dangerous - https://github.com/JustArchi/ArchiSteamFarm/issues/127

**Comment by Netshroud** [comment]
There's a difference between code-signing and strong-name signing, and I've never seen an AV look for strong-name signing as it's purely a CLR construct, not a general-purpose security construct.

I think it would be best if you could determine **why** ASF is triggering two antivirus engines rather than just throwing things at the wall and seeing what sticks, both for ASF itself and your dependency tree.

**Comment by JustArchi** [comment]
> I've never seen an AV look for strong-name signing

Me neither, yet for some reason it seems that signed assembly works around that issue, various developers at StackOverflow don't know either why, yet it's being suggested in such cases, and solves the problem.

> I think it would be best if you could determine why ASF is triggering two antivirus engines

Just one now, and it's been known for being rather poor choice, hence I don't even care that much - what worried me is that Windows Defender heuristically decided that something is naughty in my assembly as well, while after signing all is quiet and OK.

There's no issue in the code itself that could even trigger such behaviour, as my code doesn't even use any unsafe structs such as pointers, memory access or so. Looking for the culprit in this case is pointless.

**Comment by Netshroud** [comment]
Perhaps it's best to get a proper answer than just guessing. https://www.microsoft.com/en-us/security/portal/developer/ContactUS.aspx

**Comment by JustArchi** [comment]
I did send a request regarding my assembly already through above form, and I'm still waiting for a reply. In the meantime, I'm doing my own research and bullet-proofing what I can, which also includes signing assembly I'm doing at the moment.

I can't see how releasing signed SK2 library on nuget could hurt, I couldn't see any disadvantages of such approach, as it can only help ASF, and other SK2-based projects, if they wanted to release signed assemblies based on them.

**Comment by Netshroud** [comment]
I'll leave this for other members to add to the discussion, this is just my position.

---

Strong-name signing is different to code-signing. It's a CLR construct, not a generic construct like TLS or Authenticode.

The strong name becomes part of the assembly's identity. This can and likely will break compatibility - not just for our consumers but _also for consumers of our dependants_, e.g. people who use Paralin's Dota 2 library. I'm not sure how NuGet will handle dependency resolution if one version is signed and another is unsigned - it's effectively the same as SteamKit 1.7 being "SteamKit, 1.7.0" and SteamKit 1.8 being "SteamKitABC, 1.8.0".

Strong-name signing is only useful in limited circumstances:

1. **The assembly needs to be installed in the GAC.**
I really hope nobody is installing SteamKit2 in the GAC.

2. **Multiple versions of the assembly need to be loaded side-by-side in the same AppDomain (e.g. dependencies for a Visual Studio extension)**
If you have a legitimate need for this we can investigate it, but so far nobody has raised this issue.

3. **You're deploying an application and don't want somebody to be able to swap one of the dependent assemblies for a different one that happens to have the same name and API surface.**
This is a bit of a security-paranoid reason, but is somewhat useless for an open-source project. Either we have to retain publishing control by making everything open except for the strong-name signing key (not good), or we commit the strong-name signing key to source control (also not good).

I hardly think "My users' antivirus is shit, please break compatibility and take on this extra maintenance burden because this somehow magically influences the antivirus for reasons I don't understand" is sufficient justification to introduce strong-name signing.

**Comment by JustArchi** [comment]
> You're deploying an application and don't want somebody to be able to swap one of the dependent assemblies for a different one that happens to have the same name and API surface.

This is actually legit reason for me as well, as when I'm providing ASF executable that depends on 4 other DLL libraries, I'd want to ensure that user won't replace one of those libraries with some other version, that might break compatibility and cause issues I won't even be able to reproduce. So while I can't see a purpose of 2 first reasons, last one is definitely an extra reason added to my request.

I'd also want to point out, that all other libraries I'm using in my projects, including ```HtmlAgilityPack```, ```Newtonsoft.Json``` and ```protobuf-net``` include ```PublicKeyToken```, so SK2 is the only library stopping me at the moment from releasing fully signed assembly. It's a common approach to sign libraries, majority of all libraries available on nuget come signed, so I really don't know why we're asking "why we should be doing that" instead of "why we should not be doing that". Personally I can't see a reason for doing that, but I'm only kindly asking to consider doing so, it's your project and you're the one who decides whether the case is valid or not, in the worst scenario I'll need to clutter my dependency tree even further and release my own signed version of SK2.

**Comment by Netshroud** [comment]
Yet as I stated above, the justification (3) is useless if we strong-name but commit the signing key, as many other signed projects do. So if that is the sole reason, it won't help you if we go that route.

Additionally, the user may replace one of those libraries with another version of a strong-named library from the vendor and use assembly binding redirects. This also doesn't solve that issue.

Beyond that, Microsoft's [current recommendation](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md) is that strong-naming is no longer needed and only required in rare situations as outlined above, so it is definitely valid to ask "why should we do this" rather than "why should we not do this".

In general, any project should assess the value of any change and ask "why should we do this". If the answer is simply "that is what .NET libraries should do because X Y Z" then that may be sufficient answer and sufficient value, but that is not the answer I see here.

Other libraries such as `Newtonsoft.Json` etc. do meet some of the above requirements, or their dependencies do. For example, `StyleCop.Analyzers` is a Roslyn Analyzer, thus meets criteria number (2) above and depends on `Newtonsoft.Json`.

Furthermore, `Newtonsoft.Json` is an old library going back nearly 10 years and has undoubtedly had many similar issues with consumers. SteamKit is a new-ish project, and does not have the legacy of decisions and traditions from last decade to hold to. It's hardly a fair comparison.

Given what I know of strong-name signing, I'd recommend that you don't strong-name ASF. To be blunt, it seems like a shitty workaround for a stupid problem and, as is evident from this issue, contagious.

**Comment by JustArchi** [comment]
> To be blunt, it seems like a shitty workaround for a stupid problem and, as is evident from this issue, contagious.

Agreed, I don't like it either, but that's my problem. Still, I think it won't hurt to release SK2 library as signed, but that decision I leave upon you. If you (and the rest of the team) decide that you don't want to do that, just close the issue and that's it - no hard feelings.
