### ISSUE TITLE
Disconnect user from Steam

### ISSUE THREAD

**Issue by FindedLine** [SteamRE/SteamKit#277]
Hello,

When I'm connecting with Steamkit to my Steam account (using C# Console Program), It disconnect my main Steam Account (with Steam), and display this error on Steam (translate from French): A connection to the friend's network can not be established. Steam will try to re-connect to it... 

regards

Sorry for bad english

**Comment by DoctorMcKay** [comment]
You need to set the [loginID](https://github.com/SteamRE/SteamKit/blob/32c1a6f3794ba61554a3a38c94e339068b2633d3/SteamKit2/SteamKit2/Steam/Handlers/SteamUser/SteamUser.cs#L40-L50).

**Comment by FindedLine** [comment]
Perfect, thanks.

**Comment by JustArchi** [comment]
And because of nature of this field, I suggest to set it to ```MsgClientLogon.ObfuscationMask``` as in **[ASF](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Bot.cs#L49)**. This is because the LoginID is further XORed on Steam network to get private IP, and using obfuscation mask as LoginID causes return value of 0, which is better than potentially invalid result IP.

That's only a suggestion though.
