### ISSUE TITLE
.NET Core Support

### ISSUE THREAD

**Issue by Netshroud** [SteamRE/SteamKit#299]
TODO: Investigate value and feasibility.

Looks like protobuf-net 2.1.x(-alpha) supports .NET Core.

**Comment by JustArchi** [comment]
Would be lovely, I'm messing with .NET Core lately and support from dotnet on Linux works much better than Mono. Thanks for considering :+1:

**Comment by VoiDeD** [comment]
With the recent news about .NET Standard 2.0, we may wish to look to that
instead of targeting Core directly.

**Comment by Netshroud** [comment]
Ooh, that's a nice surprise.

 I was going off [this table](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md), but [this one](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) for v2.0 is a drastic improvement.

**Comment by TimotheeJeannin** [comment]
It would be awesome to have linux support for **NetHook2** as well. Can **NET Standard 2.0** help for this ?

**Comment by Netshroud** [comment]
Nope. NetHook2 is fully native, and needs to be re-thought for OS X and Linux.

The good news is we have `LD_PRELOAD` and `DYLD_INSERT_BINARIES`. The bad news is I have no idea how to detour the existing code.

Either way, completely separate issue/project/thing.

**Comment by shravan2x** [comment]
So **.NET Core 2.0** (Which implements **NET Standard 2.0**), has been delayed until Q3. In light of this, should we try to push forward without it?

**Comment by Netshroud** [comment]
.NET Standard 2.0 tooling was supposed to ship with Visual Studio 2017 RTM, which is two weeks from today.

If that doesn't happen (it wasn't in any preview builds, so I won't be surprised if it slips or ships horribly broken), we can re-evaluate.

Otherwise, there may be a way to run .NET Standard 2.0 libraries on .NET Core 1.0/1.1/1.2... we'll have to wait and see what happens at //build.

**Comment by shravan2x** [comment]
Yeah, but it's been postponed. Check the roadmap at https://github.com/dotnet/core/blob/master/roadmap.md. As such, I really doubt it would be shipped with VS2017. I think we should re-evaluate.

**Comment by Netshroud** [comment]
As far as I am aware, VS2017 still brings:
* RTM version of MSBuild-based SDK for .NET Core
* Improved multi-targeting supports

Both are useful for us, particularly multi-targeting. We'd probably want to target .NET Standard 1.1-1.5 (I vote for at least 1.3), and still ship a full-framework assembly (I vote net45 or net46, as Mono stable now supports up to .NET 4.6) so that we can take advantage of desktop-only APIs such as `IsolatedStorage` when running in full-framework environments.

**Comment by JustArchi** [comment]
IIRC Microsoft wanted to use 4.6.1 as a framework version that should support all .NET Core 2.0 features, so it'd probably help you in long-run if you targetted .NET 4.6.1 as non-core version - this is also my vote if you'd like to hear my opinion.

Ref: https://github.com/dotnet/standard/blob/master/docs/versions.md#net-standard-versions

I'm building my ASF with SK2 on Mono and it works flawlessly on 4.6.1 since a few versions already (4.2+), it'll only improve with time.

**Comment by Netshroud** [comment]
My understanding is that 4.6.1 is their maximum, i.e. the new APIs from 4.6.2 will not be available in .NET Standard 2.0 / .NET Core 2.0.

In theory we shouldn't push our requirements higher than we need - if 4.5 is enough, no reason to go higher.

I've found `Task.CompletedTask` and `FormattableString`/`FormattableStringFactory` (compiler implementation details) to be useful on other projects, if they're useful here then we should consider using 4.6. I don't see any benefit to requiring 4.6.1 for all consumers, though.

**Comment by JustArchi** [comment]
Well there is not a big difference API-wise between 4.6 and 4.6.1, I was simply preferring 4.6.1 since Mono supports it OOB together with 4.6, and everybody having .NET 4.6 almost always have it in version of 4.6.1 or even higher for now, but yeah library-wise it'd probably be better to target .NET 4.6.

However, .NET 4.5 vs .NET 4.6 is much more obvious, since .NET 4.6 adds pretty nice changes from which SK2 could benefit in long-run, such as **[this](https://github.com/JustArchi/ArchiSteamFarm/blob/c426ddece7524ef0cf0d5fa18b7bfd87421ead48/ArchiSteamFarm/Utilities.cs#L62)**. If you have to decide between .NET 4.6.1 and 4.6, it can be anything, but for .NET 4.6 vs .NET 4.5, it should be definitely .NET 4.6 imho, but that's still only my opinion.

**Comment by shravan2x** [comment]
I vote we stay at the highest version supported by both, i.e. 4.6.1. Even if it doesn't bring significant changes API wise, it could only be better on the security and performance fronts.

**Comment by shravan2x** [comment]
Bumping because [VS2017](https://www.visualstudio.com/vs/whatsnew/) is out.

**Comment by VoiDeD** [comment]
https://github.com/SteamRE/SteamKit/compare/netcore-for-realsies

@Netshroud is diligently working on it.
