### ISSUE TITLE
Protobuf v3.0.0

### ISSUE THREAD

**Issue by adamb70** [SteamRE/SteamKit#312]
Google have recently released [proto3](https://github.com/google/protobuf/releases/tag/v3.0.0) which claims better resource usage, and they have added support for some new languages natively.

I'm not sure it's worth rebuilding all the proto2 files to proto3 now, but it might be useful info for anyone starting on a new project.

**Comment by Netshroud** [comment]
I think this would mostly depend on whether the protobuf descriptors (`descriptor.proto`) are compatible between proto2 and proto3. If they are, it's a new decision to make. If they aren't, we can't do anything.

**Comment by seishun** [comment]
1. You're confusing proto3 (syntax version) with Protobuf v3.0.0 (compiler and library version).
2. Valve uses proto2 exclusively. It's not compatible with proto3.
3. SteamKit2 uses protobuf-net, so a new version of library/compiler from Google is irrelevant. Unless you're proposing to switch to their implementation, which would be a different topic.

**Comment by Netshroud** [comment]
1. Google's protobuf C# codegen does not support proto2, so it would have to be an entire switchover to proto3.
2. It's still wire-compatible, it's not an entirely new system.
3. As far as I know, we only use protobuf-net because there was no first-part C#/.NET implementation. Now there is.

We can only really use the first-party implementation if we also use the protoc first-party compiler (which protobuf-net should really have hooked into all along, but instead went with it's own funky XSLT stuff around protoc, AFAIK).

We can only use that if we generate proto3 files, since Google's C# codegen does not support proto2.

We can only do that if we can dump proto3-compatible files from Valve's proto2-based binaries.

So as I said above, it really comes down to how compatible ProtobufDumper would be with using proto2 descriptors to generate proto3 files.

**Comment by seishun** [comment]
>We can only do that if we can dump proto3-compatible files from Valve's proto2-based binaries.

Even if this is possible, it would at the very least lose information, since proto3 doesn't support default values for fields.

**Comment by adamb70** [comment]
My mistake, I did confuse proto3 and Protobuf V3.0.0.

I see, so unless Valve switched their whole system to proto3 we won't be seeing any changes here. Thanks anyway.

**Comment by Netshroud** [comment]
Yep. We'd probably have to wait for Valve to make the switch, I have my doubts they ever would.
