### ISSUE TITLE
WebAPI.GetAsyncInterface() is missing Timeout property

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#381]
As initially stated in #379:

Async interface returned by `WebAPI.GetAsyncInterface()` doesn't have `Timeout` property like its non-async version. Since it uses `HttpClient` under the hood, and that one can have custom `Timeout` property, I think it should be added.

In my code instead of:

```
HttpClient = new HttpClient();
```

I'm using:

```
HttpClient = new HttpClient {
	Timeout = TimeSpan.FromMilliseconds(60 * 1000) // Or anything user provides as int, I used FromMilliseconds to keep compatibility with non-async interface
};
```

Is there anything problematic regarding this in .NET core? I'm looking for a possible reason why @Netshroud decided to omit it as stated **[here](https://github.com/SteamRE/SteamKit/issues/379#issuecomment-290259479)**.

https://github.com/SteamRE/SteamKit/blob/f41261be563d6b999be3e46102c77e4768074e76/SteamKit2/SteamKit2/Steam/WebAPI/WebAPI.cs#L220

Thanks!

**Comment by yaakov-h** [comment]
OK, I see a couple ways to do this, and I'm not quite happy with any of them. 🙃 

`WebAPI.Interface`'s timeout is in milliseconds which kind of sucks - `TimeSpan` is much better for this kind of thing.

`WebAPI.Interface` blocks waiting for an asynchronous call to complete, and if it doesn't complete before the timeout, it simply throws a `TimeoutException`, and doesn't cancel the asynchronous call.

If `WebAPI.AsyncInterface` had a `Timeout` property that was just a proxy to `HttpClient.Timeout`, they would have different types, behave differently and throw different exception types (`TimeoutException` vs `TaskCanceledException` [a subclass of `OperationCanceledException`]).

The cleanest way to do this is probably for `AsyncInterface` to expose `HttpClient.Timeout`, and then `Interface.Timeout` will proxy to `Interface.asyncInterface.Timeout`. In this case we should then just wait for `callTask` and throw whatever exception it throws - even `OperationCanceledException` - by using `.GetAwaiter.GetResult()` rather than `ExceptionDispatchInfo`.

**Comment by JustArchi** [comment]
> WebAPI.Interface's timeout is in milliseconds which kind of sucks - TimeSpan is much better for this kind of thing.

We could change internal API to use TimeSpans and leave old timeout property as `get => TimeoutTimeSpan.TotalMiliseconds` and `set => TimeoutTimeSpan = new TimeSpan(0, 0, 0, 0, value)`. This way it wouldn't break API, while using timespans under the hood. This is just an idea as something that seems very clean to me. We could further deprecate Timeout and tell people to use newly added timespan, eventually getting rid of this in some future version.

As for other things the only thing that comes to my mind is wrapping those exceptions and decide upon a single scheme. There is no issue in catching `TaskCanceledException` and throwing `TimeoutException` or vice-versa. Question is if this is appropriate, maybe another solution would be something like new `SteamApiTimeoutException` that would inherit from `TimeoutException`? Just random ideas.

**Comment by yaakov-h** [comment]
I'm fine with breaking public API to make it more sensible when changing the major version. 😄 

I'll see if I can get this done in the next couple of days.
