### ISSUE TITLE
CDOTAMatchMetadataFile

### ISSUE THREAD

**Issue by STRATZ-Ken** [SteamRE/SteamKit#392]
File Path : SteamKit/Resources/Protobufs/dota/dota_match_metadata.proto

This variable (`CDOTAMatchMetadataFile`) is missing in the latest build (Alpha 4), the file exists in the repo, but the variable cannot be called within the `using SteamKit2.GC.Dota.Internal`

**Comment by VoiDeD** [comment]
SteamKit usually only includes GC related protobuf messages, are the messages in `dota_match_metadata` exposed over the network?

**Comment by STRATZ-Ken** [comment]
No, they are not.  We just use this class so we can download (HTTP) and extract the data from it.  We don't use SteamKit for it, but it would be nice to have this class available for use if possible.  It was previously available in 1.8.3

**Comment by psychonic** [comment]
The match metadata does get downloaded over HTTP, but to do so, relies on data only available directly from the GC. I think we should probably include these. I think we were before the Dota protos got split up.

@VoiDeD thoughts?

**Comment by VoiDeD** [comment]
Totally fine by me to include them.

@STRATZ-Ken I would, however, recommend that you maintain your own copy of the protobufs, and generated versions of them.

We try to do a best effort to keep our generated protobufs up to date, but can't guarantee fast turnaround times on getting them updated since changes wouldn't be available until the next release.

If you maintain your own versions, you can update them as fast as you need to.

**Comment by STRATZ-Ken** [comment]
@VoiDeD I agree, we normally don't update very often as very rarely do we need the newest stuff, I did notice you had some upgrades to the connection process in the last submits and I always thought there is something wrong with connecting with a lot of bots on a single machine.  I was hoping the upgrade would help.  (Also upgraded from 4.5 to 4.6 .Net in the process with SteamKit :) )
