### ISSUE TITLE
Steam Trading

### ISSUE THREAD

**Issue by Danielix99** [SteamRE/SteamKit#406]
why no one cares about trading, why there is so weak support for trading in steamkit2? i believe thats creating an unique library that support almost all steamclient features would be better, because now i need to stop using this beautiful lib in c# and start learning nodejs, that kinda lib cant accept a trade too...

**Comment by DoctorMcKay** [comment]
SteamKit is designed for communicating with the CM as the Steam client does. Trading goes over HTTP, so it's out of scope for SteamKit.

**Comment by JustArchi** [comment]
> now i need to stop using this beautiful lib in c# and start learning nodejs

That only proves you have zero idea about what SK2 is.

**Comment by Danielix99** [comment]
but theres no c# support for trading, no one wanna create a lib except jesse..

**Comment by JustArchi** [comment]
> but theres no c# support for trading

Then you also have no idea what my ASF is 🙂.

**Comment by Danielix99** [comment]
ok if im in wrong i'm sorry, can someone just help me to find some lib that implement the trade part 2
?

**Comment by JustArchi** [comment]
That's much better than assuming SK2 is wrong and nobody cares 🙂.

Here you go - https://github.com/JustArchi/ArchiSteamFarm, especially ArchiWebHandler will be useful for you.

**Comment by Danielix99** [comment]
i'm sorry, but can someone give me some doc about how trading works in steam? because reading jesse bot system is very tedious..

**Comment by Danielix99** [comment]
Thanks bro, i will check it soon

**Comment by JustArchi** [comment]
Learning how ASF deals with Steam trading, then checking in the source code how it's exactly done would be my suggestion if you want to learn how that specific Steam part works. Many devs told me that ASF source code is excellent, so I tend to recommend it when somebody asks how given thing that ASF implements is exactly achieved - especially because SK2 is the only Steam-based library that ASF makes use of.

ASF is not library though, and SK2 is not the proper place to discuss it, so treat it more like just a helpful hand where to look for working implementation. If you're determined enough to learn, that will be much more than enough, and if you're working for code to copy-paste then ASF won't be much of use.

**Comment by Netshroud** [comment]
Closing as answered by @DoctorMcKay.
