### ISSUE TITLE
Best practices?

### ISSUE THREAD

**Issue by leonard-thieu** [SteamRE/SteamKit#480]
Is there a set of best practices for using SteamKit (v1.8.3)?

I find myself running into hangs/deadlocks a lot and I believe it's due to my usage of SteamKit. These issues tend to be difficult to isolate and debug. I'm thinking that better usage through best practices would be an efficient way to deal with this.

**Comment by VoiDeD** [comment]
Can you describe your deadlocks? We don't document it very well, but for the most part any method that interacts with networking should be thread safe.

The samples are usually a good starting point for how to utilize the library.

**Comment by leonard-thieu** [comment]
Right now I'm running into an issue where calling `Disconnect()` never returns. If I don't bother calling `Disconnect()`, my application still fails to exit (I'm guessing SteamKit may have a foreground thread running?). 

In terms of usage, I'm running a message loop on a background thread to run callbacks ([implementation](https://github.com/leonard-thieu/toofz-leaderboards-core/blob/64293f4db286ebfc06c3031f0f7b3491248ab05a/toofz.NecroDancer.Leaderboards/Steam/ClientApi/SteamClientAdapter.cs)). Note that I'm running on a [fork of v1.8.3](https://github.com/leonard-thieu/SteamKit), however the only [difference](https://github.com/leonard-thieu/SteamKit/compare/4eb340ecbf0686003ae3fa02296ce435e295ae5e...HEAD) is that I added interfaces for some types.

**Comment by xPaw** [comment]
Your `MessageLoop` thread is most likely keeping the app alive.

**Comment by leonard-thieu** [comment]
I created it as a background thread though. Shouldn't that allow the app to exit?

**Comment by yaakov-h** [comment]
Can you call into the never-returning `Disconnect()` and break in the debugger? That should give you some indication as to what lock we're waiting for, and what's happening on other threads to prevent disconnecting.

I think our `TcpConnection` thread is not marked as `IsBackground`, so the CLR would keep running - according the docs, I've never actually witnessed this behaviour in practice.

That said, the networking has changed a lot since 1.8.3, and it's possible that whatever deadlock you're hitting no longer exists in 2.0.

**Comment by leonard-thieu** [comment]
> Can you call into the never-returning Disconnect() and break in the debugger? That should give you some indication as to what lock we're waiting for, and what's happening on other threads to prevent disconnecting.

Makes it up to this line:
https://github.com/leonard-thieu/SteamKit/blob/462edf96923d1178eaab5a31b7b490b226b099f8/SteamKit2/SteamKit2/Networking/Steam3/TcpConnection.cs#L247

**Comment by yaakov-h** [comment]
And what’s the network thread doing at that time?

**Comment by leonard-thieu** [comment]
Looks like it's the thread that's handling the disconnect. Should that be happening?

![devenv_2017-10-24_16-59-54](https://user-images.githubusercontent.com/5265970/31967777-de09a6d4-b8dc-11e7-9048-e87ec70956e2.png)

**Comment by yaakov-h** [comment]
How on eareth did the TcpConnection threas land up in non-SteamKit code (MainAsync)?

Do you see the same behaviour with SteamKit 2.0? If so, can you please build a [MCVE](https://stackoverflow.com/help/mcve)?

**Comment by leonard-thieu** [comment]
https://github.com/leonard-thieu/SteamKitDeadlock
Minimal repro targeting 2.0.0-Beta.1.

**Comment by yaakov-h** [comment]
![sk2_deadlock_stack](https://user-images.githubusercontent.com/426009/31989237-71c1236c-b9bd-11e7-9c16-467fd9c85632.PNG)

Here's the full stack trace. Now the deadlock is starting to make sense... `Disconnect()` is waiting for a lock that is never set, because it can only be set by continued execution of `NetLoop()`, which is blocked ultimately waiting for `Disconnect()` to finish...

You can work around this for the moment by adding `await Task.Yield();` before the end of the `using` block, so that `Dispose()` gets called after rescheduling on the current `SynchronizationContext`, rather than continuing off the thread that the `AsyncJob` was finished on.

We could also yield internally in `AsyncJob`... @VoiDeD what do you think?
