### ISSUE TITLE
`SteamUserstats.FindLeaderboard` doesn't indicate failure if a leaderboard could not be found

### ISSUE THREAD

**Issue by leonard-thieu** [SteamRE/SteamKit#483]
Calling `SteamUserStats.FindLeaderboard()` with a name of a leaderboard that does not exist returns a response with `EResult.OK` and `ID == 0`. In my code, I had made the assumption that a response with `EResult.OK` is valid and therefore the data returned is valid. This turns out to be a poor assumption but I don't think it's obvious that I had to do this.

I think SteamKit should indicate failure somehow in this situation. Possibilities include:
* Setting `Result` to a value that is not `EResult.OK`.
  * I'm not sure if `EResult` represents something in the underlying Steam Client protocol. If it does, then this would be overloading the semantics of it and would be a poor choice.
* Adding an `IsValid` property.
* Throwing an exception.

**Comment by VoiDeD** [comment]
The `EResult` you're getting back is coming directly from Steam, SteamKit isn't doing much in this case other than wrapping the request and response messages.

There might be additional logic the real Steam client is doing when `OK` is paired with an ID of 0, but we'd have to disassemble to find out more.

I would imagine the callback properties represent something like:

`FindOrCreateLeaderboardCallback.Result` - whether or not the request was successful (the client had permissions, sent correct parameters, etc)
`FindOrCreateLeaderboardCallback.ID` - the ID of the leaderboard if found, otherwise `0`.

**Comment by Ne3tCode** [comment]
https://partner.steamgames.com/doc/api/ISteamUserStats#LeaderboardFindResult_t

| Name | Type | Description |
| ---- | ---- | ---- |
| m_hSteamLeaderboard | SteamLeaderboard_t | Handle to the leaderboard that was serarched for. **0 if no leaderboard was found.** |
| m_bLeaderboardFound | uint8 | Was the leaderboard found? **1 if it was, 0 if it wasn't.** |

¯\\\_(ツ)\_\/¯

**Comment by yaakov-h** [comment]
What Steam exposes via Steamworks and how it operates internally can be two completely different things, @Ne3tCode.

**Comment by Ne3tCode** [comment]
@yaakov-h at least it explains why zero is a valid value.
