### ISSUE TITLE
Cancelling a connection in progress

### ISSUE THREAD

**Issue by leonard-thieu** [SteamRE/SteamKit#495]
What's the recommended way to cancel a connect in progress? From skimming the code, it seems like I can just call `Disconnect`, although I'm not sure if it's supported through the entire connect process.

**Comment by JustArchi** [comment]
`SteamClient.Disconnect()` will work and with proper code it should always issue appropriate logic, regardless in what state the actual connection is, that's why we have a library in the first place.

What I'm doing is basically having my `SteamClient`, `CallbackManager` and `bool KeepRunning`. I spawn task responsible for `CallbackManager.RunWaitAllCallbacks()` that works in `while (KeepRunning || SteamClient.IsConnected)`, then I just send first `SteamClient.Connect()`.

When I feel like disconnecting, regardless of state, I just set `KeepRunning` to `false` and call `SteamClient.Disconnect()`.

If you're interested in more code and less documentation, then feel free to take a look at my **[ASF](https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/Bot.cs)** which makes use of a major portion of SK2 functionality.

**Comment by leonard-thieu** [comment]
Can it cancel while https://github.com/SteamRE/SteamKit/blob/f839e4d2a3dbd10eb347f541e17843cb70975a01/SteamKit2/SteamKit2/Steam/CMClient.cs#L154 is in progress?

Also, a bit tangentially related, but it looks like `ConnectionTimeout` doesn't take into account the time needed to get server candidates. Can you confirm that that's the case?

**Comment by yaakov-h** [comment]
It appears the answers are "no" and "correct", in that order.

**Comment by yaakov-h** [comment]
To clarify on the first - you can cancel the connection, but `GetNextServerCandidateAsync` will run until completion, and only then will the connection attempt abort.
