### ISSUE TITLE
ObjectDisposedException for websocket

### ISSUE THREAD

**Issue by JustArchi** [SteamRE/SteamKit#524]
![websocket](https://user-images.githubusercontent.com/1069029/36321154-1aa1c146-1349-11e8-88e6-5757228b25a0.png)

Sadly I don't have any more info regarding this, neither I can reproduce it myself. Perhaps stacktrace will be enough to guess what is wrong.

**Comment by JustArchi** [comment]
I managed to reproduce it by calling `SteamClient.Disconnect()` routine near end of my program. I'm not sure at this point if above is side-effect of `Environment.Exit()` call executed right after disconnect, or `SteamClient.Disconnect()` alone. It could probably be ignored in first case, but perhaps we can do something about it anyway.

In the meantime I'll try to reproduce it in more sane conditions.

**Comment by xPaw** [comment]
If the throwifnotconnected is to be believed, then this would be caused by calling Send() while disconnected. Since this issue was opened, there were extra asserts added surrounding the connection code. If you run with the DebugLog enabled that may reveal more info, assuming this error even still occurs.

**Comment by JustArchi** [comment]
@xPaw I did not reproduce this ever again, and there were a lot of changes in SK2 userbase since then. If you ask me, this issue can probably be closed until somebody manages to reproduce this with current codebase.
