### ISSUE TITLE
Timestamps in NetHook2

### ISSUE THREAD

**Issue by shravan2x** [SteamRE/SteamKit#583]
Could we include timestamps of dumped messages from NH2 and include a column in NHA2 for these? They would be very useful for long debugging sessions.

Possible solutions are:
1. Include a timestamp in the file itself. This would be the cleanest option, but if the file only supposed to contain raw binary data that Steam sends us, we might not want to add meta information in it.
2. We could include a timestamp in the file name. I'm not the biggest fan of unix timestamps, but if we use a `ulong`, we don't have the Y2k38 problem. I think this is the cleanest option of the three.
3. We could just use the file creation time from Windows. This could easily be inaccurate if the files have been moved around (I'm not an expert of this though).

I might be able to help with a PR if this is something we want.

**Comment by VoiDeD** [comment]
For 3, `File.GetLastWriteTime` should solve the problem of files being copied. From a cursory test on my win10 machine, copying a file via explorer seems to retain the modified timestamp - but the creation timestamp is indeed getting updated.

This would probably be the easiest approach to implement, the rest would require considerations for backwards compatibility with differing version of dumps and NHA (if we even care about this).

**Comment by shravan2x** [comment]
I suppose, but it isn't the most reliable metric.

The file might get deleted+recreated by some file syncing software like Gdrive, Dropbox, etc. Or it might get uploaded to a file hosting service that doesn't support timestamps. Or it might be moved to a filesystem that uses a different timestamp system. Or it might get transferred over some timestamp insensitive protocol (ftp? stfp? im not sure).

I'm just playing devil's advocate. I'm not sure these are realistic use cases.

Out of curiosity, why is NHA still even being maintained? What is it used for?

**Comment by VoiDeD** [comment]
Perfect is the enemy of the good. If the modified timestamp solves your use-case, I've got no issue with approving a PR for it. We can always improve later if needed.

I will also mention that some syncing software (at least Dropbox) actually does preserve the modified date. I've got files dated from way before more recent reformats/new harddrives.

As for NHA1, I'd guess because we habitually like to keep old code around. :)

**Comment by shravan2x** [comment]
The modified timestamp works for me. I'll get to work on a PR.

**Comment by shravan2x** [comment]
@VoiDeD I'd also like to adjust the default position of the `FolderBrowserDialog` used to open the bins directory to the center of the screen. The current default causes it to overflow below and I have to move it up each time.

Problem is, `FodlerBrowserDialog` is a Windows component and the only way to do this is Win32 API calls. Would this be acceptable? Or do we currently multi-target OSes?

**Comment by VoiDeD** [comment]
@shravan2x I'm not really sure if anybody is using NHA2 via mono - I'd put my money on no since the dumping workflow is windows only, and I'd doubt anyone is doing analysis on other machines.

That said, do we need it re positioned? I'm not really sure what you mean when you say it overflows.

**Comment by VoiDeD** [comment]
@yaakov-h thoughts? I don't particularly care about coupling too tightly to windows - but I suppose we could always wrap the logic behind some platform checks.

**Comment by shravan2x** [comment]
It isn't a breaking change or anything so we could call it only when the environment is Windows. But I'm not sure if that would cause compile-time issues on Mono.

**Comment by yaakov-h** [comment]
Considering that NetHook uses Win32 calls to inject into a PE binary and hooks using Detours, I don't expect anyone to be running NHA on anything other than Windows.

That said, if they are, we _should_ be able to not-break them by guarding the win32 calls with `if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))`.

(I say should because IIRC there's something dodgy about that check being implemented at build-time instead of at run-time, but I'd expect Mono to handle it appropriately.)

**Comment by JustArchi** [comment]
`RuntimeInformation.IsOSPlatform(OSPlatform.Windows)` returns `false` on Linux Mono, so that one is good to go @yaakov-h. Keep in mind that it will still return `true` on Windows Mono (yes, it exists).

If you ever need to test something against being run with mono explicitly (and not just OS), I found out probably the best possible way to achieve this:

```c#
internal static bool IsRunningOnMono => Type.GetType("Mono.Runtime") != null;
```

I use it in my ASF code to workaround broken/non-existing Mono functionality.

**Comment by yaakov-h** [comment]
@JustArchi which is fine, because Win32 should be available under Windows Mono 😉 

Though my question was most what happens if you compile on Windows (Mono or .NET) and run on Linux (Mono).

**Comment by shravan2x** [comment]
Take a look at my code at https://github.com/SteamRE/SteamKit/pull/584/commits/001fe46ad43b3e3efb6a78ac7fca24e3bd507c67 for centering the window. This code works for me.

Would we be better off using macros as in https://stackoverflow.com/questions/142508/how-do-i-check-os-with-a-preprocessor-directive ?

**Comment by yaakov-h** [comment]
That code looks a lot like a particular answer on Stack Overflow. 😉 

I just tested and for me the window does get centered on the main display already, so I'm not quite sure of the problem you're trying to solve with this.

Does changing `.ShowDialog()` to `.ShowDialog(this)` change your default positioning at all?

**Comment by shravan2x** [comment]
Yeah, I made sure to give him credit in a little comment at the top.

I'm not sure how the dialog gets centered for you, but I'm not the only one having this issue (https://social.msdn.microsoft.com/Forums/en-US/5cdb9e43-e7d6-4b73-909b-95cd900f6da2/folderbrowserdialog-screen-location?forum=csharpgeneral).

Changing `.ShowDialog()` to `.ShowDialog(this)` does not help.

**Comment by yaakov-h** [comment]
That's from 8 years ago.

What version of Windows are you running? It looks like you have some kind of custom theming, which could be causing problems.

**Comment by shravan2x** [comment]
I'm running Windows 10 build 1803, vanilla without any theming whatsoever.

**Comment by yaakov-h** [comment]
As am I... so why does your Browse For Folder dialog have a black titlebar?

**Comment by shravan2x** [comment]
I'm actually more impressed that it centers correctly for you. I've had centering issues with native Windows dialogs for ages across multiple desktops+laptops.

It might also be a DPI issue, I'm on a 4k screen.

**Comment by shravan2x** [comment]
> As am I... so why does your Browse For Folder dialog have a black titlebar?

Settings > Personalization > Colors

**Comment by shravan2x** [comment]
@VoiDeD @yaakov-h Updates on this?

**Comment by yaakov-h** [comment]
I'm happy to merge the timestamp work on it's own, but I think the windowing issue needs further investigation as to what's actually happening and, if it is a Windows bug, whether we want to work around it, or just nag MS to fix it.

They should definitely be two separate PRs.

**Comment by shravan2x** [comment]
This isn't a Windows bug - it isn't a _bug_ at all. Screen centering simply isn't a feature that `FolderBrowserDialog` offers AFAIK. I doubt MS has any chance of fixing it since it's been around for 8+ years. More importantly, they would be too afraid of causing regressions.

Like I mentioned before, I'm not sufficiently familiar with Git to split a PR by commits and it would be too time consuming to do it manually. I'll leave it up to you to either split it or wait and merge them together. I've granted you write access to my repo.

**Comment by yaakov-h** [comment]
Centering a window isn't the issue, it's your desired solution. The problem seems to be Windows deciding to show a new window by positioning it so that part or most of the window is off-screen.

I'll manually merge the PR up to and including d5520b3, but I'm not sure about the centering, and pulling code off Stack Overflow also comes with potential licencing issues.

(Maybe we should rebuild the UI in WPF...)

**Comment by shravan2x** [comment]
Still, I'm not sure if this is something MS will fix after so long. I'll leave it up to you.

Merging upto https://github.com/SteamRE/SteamKit/commit/d5520b337777b91ff7d51f69bf19f1d2276cf12b sounds good to me.

I've followed SO's licensing rules at https://stackoverflow.com/help/licensing , so we're good on that front.

**Comment by yaakov-h** [comment]
Closing as completed in c3f261d.
