### ISSUE TITLE
Proxy in steam client

### ISSUE THREAD

**Issue by MakcStudio** [SteamRE/SteamKit#587]
Can I use a proxy to connect to steam client? How?

mSteam.client.Connect();

**Comment by MakcStudio** [comment]
I need to boost about 1000 accounts from one PC at the same time

**Comment by yaakov-h** [comment]
This sounds incredibly dodgy...

We have #541 tracking the ability to specify a proxy server for WebAPI requests, but nothing for the CM connection itself. It’s unlikely that we would do that, without a compelling use-case.

**Comment by MakcStudio** [comment]
will I be able to do it myself in a dirtier way? I just need to specify a proxy server before authorizing each account.

**Comment by MakcStudio** [comment]
The problem occurs when you authorize more than 200 accounts in a row, so I need a proxy connection. If you can help to solve this problem, I will be very grateful

**Comment by azuisleet** [comment]
Proxy support is probably possible for SOCKS and HTTP proxies depending on the protocol. The implementation would require modifying the TCP/UDP connections and the WebSocket connection. The easiest implementation is likely the WebSocket with a standard HTTP proxy, since it is supported through the library itself.

I don't believe proxy support is a high priority at the moment since there isn't a need to defeat IP checks or rate limits for standard use cases.

**Comment by MakcStudio** [comment]
And I think that the problem is priority. For now steam is very active began to ban accounts for everything

**Comment by MakcStudio** [comment]
If it is not difficult for you, could you tell me in which files I can see the Declaration of these variables? I need work authorization and clien.send();
