### ISSUE TITLE
Sample DotaMatchRequest can't get recent match

### ISSUE THREAD

**Issue by copydog** [SteamRE/SteamKit#676]
I tried to get the old matches like 4000000000 (last year), it is totally fine. But I try to get 4700000000 (I am very sure it exists), I will get this exception. I have no idea.

```
Unhandled Exception: ProtoBuf.ProtoException: Invalid wire-type; this usually means you have over-written a file without truncating or setting the length; see http://stackoverflow.com/q/2152978/23354
```

btw, I already replaced uint with ulong to ensure I can send such large match_id.

please help.

**Comment by oxters168** [comment]
If you are getting the packet data and deserializing directly, you need to remove the header data first then continue with the deserialization. But if not, then you are probably giving the wrong type to deserialize to. More information would be helpful to narrow down what the problem is, post the code that causes this issue.
