### ISSUE TITLE
Activate Steam CD Key using SteamKit

### ISSUE THREAD

**Issue by edwardchanjw** [SteamRE/SteamKit#68]
Will it be able to activate steam cd key using SteamKit? 
Then it might be the customized long waiting feature "Activate Steam Cd Key on Web".

**Comment by X-Gamer** [comment]
Has anyone already implementet it in steamkit ?

 I also looking for it do give our forum users easy free games and so on without getting a key that only the user gets the game and not be gift able.

I look with nethook2 what will be send and get at cd key activatin but i not find in the steamkit how i can send cd key .

We can also write with skype or email or else you want if someone can help.

Regards

**Comment by Netshroud** [comment]
As said above, whilst it may be (and probably is) possible, we purposefully do not expose this via SteamKit. Regardless, implementing it via SteamKit would require your users to grant you full control of their account (username, password and SteamGuard) in order to implement, which nobody should ever do.

If you are the publisher, got your keys from the publisher, or have any contacts at Valve, they may be able to provide you with direct activation via the Steamworks APIs. Humble, for example, do this.

**Comment by X-Gamer** [comment]
Hello,

Also is there a way to accept / redeem / activate a Gift with steamkit2 ? 

Regards

**Comment by Netshroud** [comment]
I believe gifts are handled completely through the Web UI, so no.

**Comment by X-Gamer** [comment]
Hello,

Also is there a way to accept / redeem / activate a Gift with steamkit2 ? 

Regards

**Comment by X-Gamer** [comment]
sry

**Comment by X-Gamer** [comment]
You think no way with steamkit2 ?

**Comment by X-Gamer** [comment]
Hello,

Also is there a way to accept / redeem / activate a Gift with steamkit2 ?

I have trade bot etc but want accept Gift etc automatic and add them do my account.

From link or from my inventory to my steam library !

Is there a way todo that ?

You think no way with steamkit2 ?

Regards

**Comment by X-Gamer** [comment]
`?

**Comment by Netshroud** [comment]
If the only thing that has changed since you last asked the question is the time, the answer won't change either.

**Comment by JustArchi** [comment]
Regarding redeeming cd-keys, it's quite easy - https://github.com/JustArchi/ArchiSteamFarm/blob/master/ArchiSteamFarm/ArchiHandler.cs#L198

Gifts are on ASF's todo list.

But I doubt that you'll be able to even understand how to implement that, as you seem to have serious problems even with reading.

**Comment by X-Gamer** [comment]
@JustArchi 
I already know / can activate keys but its not needed and only work when the other account login with steam guard.  but i use it for my account 

Also Gift with steamkit2 will be good then but atm i find no way because steam handle gifts over web. 

You think at ASF you can make it then with steamkit2 ?


Regards

**Comment by luky92** [comment]
@X-Gamer ASF uses SteamKit2 for it

**Comment by X-Gamer** [comment]
@luky92 

yes i know :)  

Thats why i asked:

Also Gift with steamkit2 will be good then but atm i find no way because steam handle gifts over web.

You think at ASF you can make it then with steamkit2 ?   

:)

**Comment by JustArchi** [comment]
SK2 is a client-based solution, if @Netshroud is right, and I bet he is, then you can't do that with SK2. ASF includes both SK2 and it's own ArchiWebHandler that is responsible for interacting with Steam Web through very own HttpClient.

It's out of the scope of SK2.

**Comment by luky92** [comment]
@JustArchi you mind contacting me?

**Comment by JustArchi** [comment]
I do not offer SK2 neither Steam-based support. I have enough of my own stuff to handle.

**Comment by X-Gamer** [comment]
@JustArchi 

When you think that with ASF Steam Gift can be activated . and can with ASF also like node steam js ?  or only at  Windows ?

**Comment by VoiDeD** [comment]
@X-Gamer your conversation has gone entirely off topic from SteamKit. Please take your discussion with @JustArchi to other channels.
