### ISSUE TITLE
🤔CMsgClientAMGetClanOfficers causing HIGH RAM USAGE ⚠

### ISSUE THREAD

**Issue by sp0ok3r** [SteamRE/SteamKit#687]
Hello, so calling this:

```
var request = new ClientMsgProtobuf<CMsgClientAMGetClanOfficers>(EMsg.ClientAMGetClanOfficers);
request.Body.steamid_clan = clanID;
steamClient.Send(request);
```

is causing steam client webhelper ram raise.

Any opinions?

![highRam_Officers](https://user-images.githubusercontent.com/7952298/58256255-974c3180-7d66-11e9-9e69-45828ac3d7a6.png)

**Comment by yaakov-h** [comment]
.... sending a message with SK2 causes one of Steam’s Chromium processes to increase its memory usage??

**Comment by sp0ok3r** [comment]
yes, turned the function off and no ram usage...

**Comment by yaakov-h** [comment]
If this is true, it doesn't seem like anything caused by SteamKit or anything that we could remedy. This would be purely up to Steam.

And there may actually be _some_ slight merit to this.

Before:

![image](https://user-images.githubusercontent.com/426009/58301385-9cbe8000-7e29-11e9-80bf-fcb9507c0354.png)

After:

![image](https://user-images.githubusercontent.com/426009/58301392-a47e2480-7e29-11e9-861b-67ccbc52c996.png)

No significant change.

Even after sending the message once every second several full minutes:

![image](https://user-images.githubusercontent.com/426009/58301541-2a01d480-7e2a-11e9-9ebe-861618c47dcd.png)

However, calling `ClientAMGetClanOfficers` from one client instance (such as SteamKit) causes the CM servers to send `ClientPersonaState` updates to other client instances (such as Steam). That bit is perfectly reproducible.

The memory leak, though, I can't reproduce.

If you're seeing a reliable and reproducible memory leak in the Steam client, contact Valve directly.
