### ISSUE TITLE
Steamguard Sample issue

### ISSUE THREAD

**Issue by cyberangel67** [SteamRE/SteamKit#691]
This is  probably a newbie error, but I am looking at the SteamGuard Example and the console hangs when the program finishes.

It appears the while(isRunning) {} section is causing it task or thread to keep running therefore holding the console open.

Is there a way to have the LoggedOn callback finish and return control back to the main loop.

Up to this point I understand what is going on, but I want the main method to do other stuff and exit and the console is not exiting.

**Comment by cyberangel67** [comment]
Ok, on further investigation I think there is an issue with the way it is structured. Maybe just me.

If I place this

            isRunning = false;

Write after the console output for Successfully logged on, then the control is returned to the main thread as it breaks the loop. But the issue then, is if I delete the Sentry.bin file, it will never be written, because that callback is never called.

I am trying to establish how this works, so that I can create a WPF Window 10 Application, but as it stands I have no idea how to even go about adding this to a WPF program.

What would be the chances of a sample application, that wold have a basic form, that when the user presses connect on then it goes does what it has to do, if it is has to be authinticated with the steamguard then pop that form back up with the code sent via email.

And all controlled via a button from the main form to login.

I know it is asking a lot, but there is just not tutorials on how to integrate this into a WPF Program that I can find via google search.

**Comment by yaakov-h** [comment]
The callback loop runs until the client is disconnected from Steam.

If you want to run something after you're connected, [this would be the most appropriate place](https://github.com/SteamRE/SteamKit/blob/e5e471dbbb1ebf910ce3893f28aedd1f8c61c32f/Samples/5.SteamGuard/Program.cs#L176).

Advanced lifecycle management isn't something we provide sample code for. There are other programs like SteamDB or ArchiSteamFarm that can probably help you in that area.

**Comment by cyberangel67** [comment]
> ArchiSteamFarm

It still doesn't solve what I need. 

And SteamDB and ArchieSteamFarm don't do what I require. I just need a simple login, auntenticate the user, so I can then use their steamID to pull data out of a game save file in a WPF Application.

I think the way these call backs are kind of badly done, I don't know enough about how they work. But like I said it works if I do the isRunning=false; in the spot I put it, but then the Sentry.Bin is never created and I would have thought that the best place to create that would be in the OnConnected and update it if successfully logged in rather than a separate callback for it.

**Comment by cyberangel67** [comment]
And the only thing blocking the main thread is the while loop only.

**Comment by azuisleet** [comment]
You need to pump the callback queue with `RunWaitCallbacks`. That's how callbacks are delivered in the library.

In a console app, blocking the main thread is sufficient. If you're building an up with a UI, you'll need to figure out a strategy for processing callbacks. You could create a thread to run `RunWaitCallbacks`. If you wanted the callbacks to run on your UI thread, you could use a timer, eg `DispatcherTimer`

**Comment by cyberangel67** [comment]
I mean, when the console finishes doing what I need it sits there until I hit CTRL+C.

I even added the steamClient.Disconnect(); in the section that was described as being the place to do what you need to do, but again the Sentry file never gets created.

**Comment by yaakov-h** [comment]
That would be because the `UpdateMachineAuth` flow on runs _after_ login (if at all).

If you just want the user's Steam ID, try Steam Community's OpenID. Or, you could use SteamWorks or OpenSteamWorks to ask the current Steam client instance very nicely for the current user's Steam ID.

**Comment by cyberangel67** [comment]
> That would be because the `UpdateMachineAuth` flow on runs _after_ login (if at all).

Exactly!!! and even as a console app, I can't even just run it as a service as it ends up with thousands of running tasks, because it doesn't open and close cleanly, it requires user intervention to CTR+C. That screams badly written code for me.

> 
> If you just want the user's Steam ID, try Steam Community's OpenID. Or, you could use SteamWorks or OpenSteamWorks to ask the current Steam client instance very nicely for the current user's Steam ID.

I have been looking for anything that allows me to sign someone in and authenticate the user, but alas there are next to zero examples out there. And people kept recommending this library, but unfortunately because of the way the sample app is written, it hangs there until a user hits CTRL+C and they is not good enough for 99.99% of peoples needs.

**Comment by JustArchi** [comment]
Sample app is not the definition how you should/can make use of the library, only sample usage for specific task. You said yourself that this isn't sufficient for your needs because of CTRL+C in the console, and I agree, but the sample shows **how to use the library**, and not how to write Steam WPF app. You take those lines of code that give you a headstart into understanding the lib and then combine it with general C# knowledge in order to make an application that satisfies your usage.

@azuisleet told you several different ways above how to achieve that. You don't need any loop to handle callbacks (if you don't want it), but you'll need to handle them one way or another. SteamDB and ASF are examples of applications built on top of SK2, and they already do things a different way, despite of both being console apps.

So no, SK2 is not unfriendly, and making use of SK2 in a WPF app isn't problematic, impossible or somehow more troublesome than doing the same in console app. If anything, you can rant that example code isn't designed as good as it could, but once again that code isn't supposed to be copy-pasted into your app, but rather give you a headstart of achieving something that works.

And lastly, if you actually went with @yaakov-h suggestion and took a look at my ASF then you'd also find out that even in a console app I don't run callback manager on the main thread, and there is literally nothing stopping you from making use of my code and putting it into WPF app, especially because ASF is already dealing with sentry files.

**Comment by cyberangel67** [comment]
So I guess showing an easy to understand example is way to hard then!!!

**Comment by yaakov-h** [comment]
> Exactly!!!

That's not something we can change though, it's not up to us.

> and even as a console app, I can't even just run it as a service as it ends up with thousands of running tasks, because it doesn't open and close cleanly, it requires user intervention to CTR+C. That screams badly written code for me.

SteamDB and ASF use this library heavily in production, SteamDB in particular as a service. [Steam Status](https://steamstat.us/) runs up hundreds if not thousands of connections with no issues. Just because you don't seem to be able to progress beyond a console application doesn't mean anything is inherently wrong.

> I have been looking for anything that allows me to sign someone in and authenticate the user, but alas there are next to zero examples out there. And people kept recommending this library, but unfortunately because of the way the sample app is written, it hangs there until a user hits CTRL+C and that is not good enough for 99.99% of peoples needs.

Replace "99% of peoples" with "my". Your needs are different to someone like Archi, who's needs are different to xPaw, who's needs are different to my own.

The sample app is an interactive console application, but that is by no means the only way to harness SteamKit2 in an application. I've personally run it in a web server over WebSocket, and I know people have tried UWP applications, and if I remember correctly there have been a couple Mono iOS/Android consumers.

We don't provide samples for every environment under the sun, else we'd be here all day writing up Windows 10 for IoT Core samples to run on a Raspberry Pi, or virtual reality friends lists with HoloLens or whatever Microsoft decides to pump out next.

Imagine if something like Newtonsoft.Json or System.Net.Http did that.

**Comment by cyberangel67** [comment]
> > Exactly!!!
> 
> That's not something we can change though, it's not up to us.
> 
> > and even as a console app, I can't even just run it as a service as it ends up with thousands of running tasks, because it doesn't open and close cleanly, it requires user intervention to CTR+C. That screams badly written code for me.
> 
> SteamDB and ASF use this library heavily in production, SteamDB in particular as a service. [Steam Status](https://steamstat.us/) runs up hundreds if not thousands of connections with no issues. Just because you don't seem to be able to progress beyond a console application doesn't mean anything is inherently wrong.
> 
> > I have been looking for anything that allows me to sign someone in and authenticate the user, but alas there are next to zero examples out there. And people kept recommending this library, but unfortunately because of the way the sample app is written, it hangs there until a user hits CTRL+C and that is not good enough for 99.99% of peoples needs.
> 
> Replace "99% of peoples" with "my". Your needs are different to someone like Archi, who's needs are different to xPaw, who's needs are different to my own.
> 
> The sample app is an interactive console application, but that is by no means the only way to harness SteamKit2 in an application. I've personally run it in a web server over WebSocket, I know people have tried UWP applications, and if I remember correctly there have been a couple Mono iOS/Android consumers.
> 
> We don't provide samples for every environment under the sun, else we'd be here all day writing up Windows 10 for IoT Core samples to run on a Raspberry Pi, or virtual reality friends lists with HoloLens or whatever Microsoft decides to pump out next.
> 
> Imagine if something like Newtonsoft.Json or System.Net.Http did that.

Well a console app example that exited cleanly would have been better than the sample that is sitting there, the other issue is that you guys are adapt at what you are doing, that's fine. But some of us are still learning and need guidance and that sample app shows that a console app can't exit cleanly at all.

Rather than beating around the bush and pushing us to projects with thousands of lines of code, i would have been simpler to explain an easy way to achieve a console app to exit cleanly.

**Comment by yaakov-h** [comment]
> Well a console app example that exited cleanly would have been better than the sample that is sitting there, 

Sample 1 exits cleanly.
Sample 2 exits cleanly.
Sample 3 exits... relatively cleanly.

You seem to have picked one of the few that leave the connection open, and somehow that's a systemic library problem?

> But some of us are still learning and need guidance and that sample app shows that a console app can't exit cleanly at all.

It's fine to learn and need guidance, but it's not fine to be aggressive and pushy, nor to demand that everything is broken except you. A little bit of humility would go a long way.

**Comment by cyberangel67** [comment]
> > Well a console app example that exited cleanly would have been better than the sample that is sitting there,
> 
> Sample 1 exits cleanly.
> Sample 2 exits cleanly.
> Sample 3 exits... relatively cleanly.
> 
> You seem to have picked one of the few that leave the connection open, and somehow that's a systemic library problem?
> 
> > But some of us are still learning and need guidance and that sample app shows that a console app can't exit cleanly at all.
> 
> It's fine to learn and need guidance, but it's not fine to be aggressive and pushy, nor to demand that everything is broken except you. A little bit of humility would go a long way.

All samples require the user to press CTRL+C to exit the console.

**Comment by JustArchi** [comment]
> All samples require the user to press CTRL+C to exit the console.

No?

**Comment by yaakov-h** [comment]
They do not. I just ran those three myself to check before posting that. If you run them directly you should see the same thing.

As I said on the other thread, "If something doesn't do what you expect, include what you expected, and what it actually did." In this case, steps to reproduce this issue would also be useful.

Are you _looking_ for an argument, or are you actually seeking help? It's becoming quite hard to tell.

**Comment by cyberangel67** [comment]
Then why does every sample require me to hit CTRL+C, every sample is stuck in a while loop, there is no exit. The only way I foudn to exit was turn isRunning to False as stated in my earlier comment, but then the sentry file is not created.

**Comment by yaakov-h** [comment]
![image](https://user-images.githubusercontent.com/426009/59682156-f774ad00-9218-11e9-9668-936e5ede6da7.png)


I'm gonna go with the you're-holding-it-wrong Apple approach, unless you can sufficiently prove otherwise.

You still haven't provided enough information to determine if this is an actual problem, even though I literally asked for it twice in the last few hours.

You're only coming across as obstinate at this point, and my patience is wearing thin.

**Comment by cyberangel67** [comment]
All I know is this, ran nuget and imported the package into a console app. Then copied and pasted the code from all the examples that pertain to what I wish to do.

Mainly the SteamGuard was the one I ran the most.

It gets stuck in this loop

`            Console.WriteLine( "Connecting to Steam..." );
            // initiate the connection
            steamClient.Connect();
            // create our callback handling loop
            while ( isRunning )
            {
                // in order for the callbacks to get routed, they need to be handled by the manager
                manager.RunWaitCallbacks( TimeSpan.FromSeconds( 1 ) );
            }`

In the main thread, that means the main thread is always running in that loop. The only way to break that is by setting isRunning to false. Which I am thinking has to be here

`            if ( callback.Result != EResult.OK )
            {
                Console.WriteLine( "Unable to logon to Steam: {0} / {1}", callback.Result, callback.ExtendedResult );
                isRunning = false;
                return;
            }
            Console.WriteLine( "Successfully logged on!" );
            isRunning = false;
            // at this point, we'd be able to perform actions on Steam
`

So when I run that it breaks, but the Sentry file is not created! If I delete that file, the console message for updating it is never displayed and the file is never created. I I removed the isRunning=false, from the position I put it then it is completely stuck in that loop. Until CTRL + C is pressed. Because there is nothing breaking it.

**Comment by cyberangel67** [comment]
I should also point out that I have tried

`        Console.WriteLine( "Successfully logged on!" );
        steamUser.LogOff();
        // at this point, we'd be able to perform actions on Steam
`

but then that defeats the purpose of the Sentry file.

And I have tried.

`        if ( callback.Result != EResult.OK )
        {
            Console.WriteLine( "Unable to logon to Steam: {0} / {1}", callback.Result, callback.ExtendedResult );
            isRunning = false;
            return;
        }
        Console.WriteLine( "Successfully logged on!" );
        steamClient.Disconnect()
        // at this point, we'd be able to perform actions on Steam
`

Which ends up in a login loop, till it breaks with an error.

**Comment by oxters168** [comment]
It would be easier to debug your problem if you uploaded the entire file that you are working with. I can't tell where you are putting the code segment that sets isRunning to false. If you are putting it in the same function as where the while loop is, then your application will definitely not work. It needs to be put in the connected handler function. If you are already doing that, then the problem could be something else that we can't see here or that I'm missing completely. So it would be easier to debug if you up uploaded the entire file on pastebin or something.

**Comment by cyberangel67** [comment]
> It would be easier to debug your problem if you uploaded the entire file that you are working with. I can't tell where you are putting the code segment that sets isRunning to false. If you are putting it in the same function as where the while loop is, then your application will definitely not work. It needs to be put in the connected handler function. If you are already doing that, then the problem could be something else that we can't see here or that I'm missing completely. So it would be easier to debug if you up uploaded the entire file on pastebin or something.

It is the OnLoggedOn() section, that is the only place that has the message Successfully Logged On and I have tried placing the setting to false in OnConnected, but then the OnLoggedOn() will not work.

**Comment by azuisleet** [comment]
You must continue servicing the callback queue (and of course keeping the connection alive) in order to receive additional callbacks. OnConnected is the callback for connection setup. Once the connection is established, you must sign into the service, such as with a SteamUser account, by calling LogOn. After that you would except the login result. Any messages triggered by the login also have to be serviced, and so on.

Your program cannot terminate until you receive all the callbacks you want to process and send all the messages you want to send. The specifics of which I have already explained: in a console app it can be a while(true) loop, and in a WPF app it can be a DispatcherTimer.

The sample app simply maintains an open connection. If you want the sample app to terminate after login, you can for example set a new flag IsComplete to true, and in OnDisconnected check the flag and clear IsRunning, preventing any re-connect attempts.

**Comment by cyberangel67** [comment]
> You must continue servicing the callback queue (and of course keeping the connection alive) in order to receive additional callbacks. OnConnected is the callback for connection setup. Once the connection is established, you must sign into the service, such as with a SteamUser account, by calling LogOn. After that you would except the login result. Any messages triggered by the login also have to be serviced, and so on.
> 
> Your program cannot terminate until you receive all the callbacks you want to process and send all the messages you want to send. The specifics of which I have already explained: in a console app it can be a while(true) loop, and in a WPF app it can be a DispatcherTimer.
> 
> The sample app simply maintains an open connection. If you want the sample app to terminate after login, you can for example set a new flag IsComplete to true, and in OnDisconnected check the flag and clear IsRunning, preventing any re-connect attempts.

Which is what I am trying to do, like I said as a console application, if I wish to spawn this from a service then exit it won't work. Because there is no where to make it exit. IsComplete is the same as isRunning, I have tried a number of things, the problem is the Sentry file. You can put all the logic in that OnLoggedOn and try to exit on completion all you like, the Sentry file is just never written.

**Comment by azuisleet** [comment]
If your program needs the sentry file, then it must wait for OnMachineAuth before it can terminate. That means you must wait for both OnLoggedOn and OnMachineAuth before you can disconnect the client or terminate your main loop.

I'm not certain if the MachineAuth callback is guaranteed for every session, so you likely need a time limit  for how long you want to wait for the callback (eg if you present a sentry file don't get a new sentry file in 10 seconds after login, you can assume the sentry file you've presented is still valid).

Also, IsComplete in that example is not the same as IsRunning because IsComplete is handled in OnDisconnected, allowing the connection to be terminated before the main loop exits.

**Comment by cyberangel67** [comment]
> If your program needs the sentry file, then it must wait for OnMachineAuth before it can terminate. That means you must wait for both OnLoggedOn and OnMachineAuth before you can disconnect the client or terminate your main loop.
> 
> I'm not certain if the MachineAuth callback is guaranteed for every session, so you likely need a time limit for how long you want to wait for the callback (eg if you present a sentry file don't get a new sentry file in 10 seconds after login, you can assume the sentry file you've presented is still valid).
> 
> Also, IsComplete in that example is not the same as IsRunning because IsComplete is handled in OnDisconnected, allowing the connection to be terminated before the main loop exits.

But that's the problem, it never runs if the file exists, it only runs when it doesn't exist. I fully explained this at the very beginning.

Making what I need to do an impossibility If anyone was to actually try this for themselves, they would see what I mean and know that it can't be done.

**Comment by azuisleet** [comment]
Sorry for the misunderstanding. You are correct that you won't normally receive the callback if you present a valid sentry file. There's no definite answer here as to whether you'll get an updated one, so you must set a deadline for an updated sentry file to end your program.

**Comment by oxters168** [comment]
It can be done, I used the samples to help me write my log in code in my Unity app without hanging the UI. It's hard to help you with a specific issue because not everyone here has worked on WPF apps before and also because we have a limited view to your code through your snippets. I think posting your entire script would definitely help us help you.

**Comment by cyberangel67** [comment]
> It can be done, I used the samples to help me write my log in code in my Unity app without hanging the UI. It's hard to help you with a specific issue because not everyone here has worked on WPF apps before and also because we have a limited view to your code through your snippets. I think posting your entire script would definitely help us help you.

At this point in time I am talking about the sample SteamGuard app, I have made it very clear so far, that this sample app hangs the console, until you press CTRL+C. There is also no way to force it to exit, because if you do, the callback for the writing the Sentry file is not run.

I have made that very clear now.

Try it for yourself.

**Comment by cyberangel67** [comment]
> Sorry for the misunderstanding. You are correct that you won't normally receive the callback if you present a valid sentry file. There's no definite answer here as to whether you'll get an updated one, so you must set a deadline for an updated sentry file to end your program.

But the question is how, because there is no way to know if the Sentry file exists or not. Making the exiting of the console app problematic.

**Comment by cyberangel67** [comment]
I should also point out that during my tests, failures all I get now with no modification with the sample steamguard file is constant disconnection messages.

<img width="669" alt="Capture" src="https://user-images.githubusercontent.com/1366816/59725758-3c78fd80-9272-11e9-832e-3af2b4cf1b31.PNG">

**Comment by azuisleet** [comment]
You know if the sentry file exists because you either provided SentryFileHash in your call to LogOn or you received a new one in OnMachineAuth. If you aren't concerned with potential updates to a sentry file, you know in OnLoggedOn if you presented a valid sentry file because the result was EResult.OK. If you didn't have a sentry file or the one you had was invalid, you would have been challenged to complete the Steam Guard email flow, thus you would expect to receive a new sentry file in OnMachineAuth after completing the challenge.

**Comment by cyberangel67** [comment]
> You know if the sentry file exists because you either provided SentryFileHash in your call to LogOn or you received a new one in OnMachineAuth. If you aren't concerned with potential updates to a sentry file, you know in OnLoggedOn if you presented a valid sentry file because the result was EResult.OK. If you didn't have a sentry file or the one you had was invalid, you would have been challenged to complete the Steam Guard email flow, thus you would expect to receive a new sentry file in OnMachineAuth after completing the challenge.

That has nothing to do with me physically deleting the file and testing what I have already mentioned.

I stated, I deleted the file and try to exit the console app, by either isRUnning = false; steamUser.LogOff(); and steamClientDisconnect();

Every single time, after being challenged the file is never created.

**Comment by azuisleet** [comment]
The new file will not be created because you are ending the program before you handle OnMachineAuth. As I explained, your program needs to handle OnLoggedOn and OnMachineAuth before it can terminate.

**Comment by cyberangel67** [comment]
> The new file will not be created because you are ending the program before you handle OnMachineAuth. As I explained, your program needs to handle OnLoggedOn and OnMachineAuth before it can terminate.

I know that, which is why I am here trying to find out how I can!!!!!

**Comment by asherkin** [comment]
That has been explained twice in detail already, I highly suggest taking the time to read over and digest the previous comments and the existing SteamKit samples before rushing to respond.

**Comment by cyberangel67** [comment]
> That has been explained twice in detail already, I highly suggest taking the time to read over and digest the previous comments and the existing SteamKit samples before rushing to respond.

where!!

**Comment by azuisleet** [comment]
The answer to "how do I handle both callbacks in the Sample" is in:
https://github.com/SteamRE/SteamKit/issues/691#issuecomment-503334562

The answer to "How do I know if the sentry file exists" is in: 
https://github.com/SteamRE/SteamKit/issues/691#issuecomment-503348015

If you have a more specific question, please feel free to re-open this issue, but I believe these answers are satisfactory and this issue is not making any further progress.

**Comment by cyberangel67** [comment]
> The answer to "how do I handle both callbacks in the Sample" is in:
> [#691 (comment)](https://github.com/SteamRE/SteamKit/issues/691#issuecomment-503334562)
> 
> The answer to "How do I know if the sentry file exists" is in:
> [#691 (comment)](https://github.com/SteamRE/SteamKit/issues/691#issuecomment-503348015)
> 


Doesn't work, I made that clear already.

> If you have a more specific question, please feel free to re-open this issue, but I believe these answers are satisfactory and this issue is not making any further progress.

**Comment by azuisleet** [comment]
I'm sorry we aren't able to help you, but I am certain the two answers provide enough details once you spend some time to review them. I will be locking this issue since there are no bugs, the intended behavior of the sample is simply to maintain an open connection. 

Turning the sample code into something you want for your program is something you will have to explore on your own, as we have all provided the necessary information, so I will be locking this issue.
