### ISSUE TITLE
Reopening SteamGuard Sample app doesn't exit the console

### ISSUE THREAD

**Issue by cyberangel67** [SteamRE/SteamKit#694]
I am reopening this, because none of the suggestions actually work at all.

I have spent 16 hours going over this and trying various suggestions, but it still stand that the callback for Sentry creation is never called, when attempting to exit the console.

There must be a better was than using callbacks in this manner.

I just don't understand why the call back is not actually called before the user is logged on, instead is created after the user is logged on.

If it was to do that, I could actually see this working out of the box without an issue.

so to reiterate, nothing in this conversation actually works

[https://github.com/SteamRE/SteamKit/issues/691](url)

**Comment by MsBehaving** [comment]
I too have seen this issue and tried all the suggestions in the previous ticket.

The problem with OnDisconnected as suggested is that it is not called at the appropriate time, for that sort of checking to happen. As I too while trying to figure this out tried many ways to get this to work.

But how do you trigger the OnDisconnect because I certainly can't find a way to trigger that and have the Sentry file get created.

I wish there was clear an precise way to achieve this.
