### ISSUE TITLE
Repeated discriminants enums.steamd

### ISSUE THREAD

**Issue by saskenuba** [SteamRE/SteamKit#793]
If I got this right, all these enums are automatically extracted from steam's client to this intermediate language called steamd.

I am currently porting the codebase to rust, and now I am at the step to write a parser to generate the msgs and enums.. so I am wondering what rule should I follow, remove the second repetition or if it shouldn't be there in the first place. I checked that the C# file has both, but the rust compiler doesn't accept that, so there has to be a rule?

Take for example the enum `EWorkshopFileType`, it has the same discriminant for both `First` and `Community`.

https://github.com/SteamRE/SteamKit/blob/8fb6ba88569c538404e6d17680fb979d8a3047a2/Resources/SteamLanguage/enums.steamd#L1039

Also, there are some discriminants with commentaries such as  `// removed` and `// obselete`. If the discriminant was renamed why not erase the whole line and put it on a changelog instead? It adds some unnecessary rules that make the parsing with a lot of edge cases.

https://github.com/SteamRE/SteamKit/blob/8fb6ba88569c538404e6d17680fb979d8a3047a2/Resources/SteamLanguage/enums.steamd#L212

 Thanks!

**Comment by VoiDeD** [comment]
>are automatically extracted from steam's client

It's actually a manual process mostly driven by either disassembly of steam's binaries or pulling it from other sources (community/chat javascript files, source code leaks, etc).

>Take for example the enum EWorkshopFileType, it has the same discriminant for both First and Community.

The reason for `First`, `Last`, `Max`, etc enum values usually stems from the original source of the enum values themselves: C/C++ code. Having a first/last enum value usually leads itself to easier code patterns where you iterate through an enum.

There's no solid rule here since the language we primarily generate to (C#) has no limitation on multiple constants having the same value. A naive approach in your parsing might be to ignore duplicates that are named `First`, `Max`, etc.

>Also, there are some discriminants with commentaries such as // removed and // obselete. If the discriminant was renamed why not erase the whole line and put it on a changelog instead?

This metadata exists to annotate the C# code with attributes that declare obsoletions. These translate into compiler warnings for end users to update their code. So _usually_ we keep around obsoleted/renamed enum values for backwards compatibility - at least where feasible.

All this said, we've already implemented a (mostly) language-agnostic parser/tokenizer that supports a few code generating frontends. You could always plug in your own generator so that at least most of the parsing work is already done.

https://github.com/SteamRE/SteamKit/tree/master/Resources/SteamLanguageParser/Generator

**Comment by saskenuba** [comment]
Thanks for explaining it @VoiDeD. I already made some fixes to the parser that are working now. Perhaps you could add my port to the SteamKit's port list? https://github.com/saskenuba/SteamHelper-rs. Also, is there a place for quick questions about steamkit internals? Thanks again

**Comment by yaakov-h** [comment]
Added to the [Ports](https://github.com/SteamRE/SteamKit/wiki/Ports) list.
