### ISSUE TITLE
Help deserializing GC Protobuf Messages

### ISSUE THREAD

**Issue by Hackerprod** [SteamRE/SteamKit#807]
Hi, I need help to deserialize the ClientToGC GC message since I am using Steamkit2 server side. Regards

**Comment by azuisleet** [comment]
You need to break apart the message layer by layer. If you're using SteamGameCoordinator the machinery is already there for MessageCallback, otherwise you would first look for EMsg.ClientToGC and break apart the network message:

`var msg = new ClientMsgProtobuf<CMsgGCClient>( packetMsg );`

Then you would parse the GC message using the helper (or something similar to) `SteamGameCoordinator.IPacketGCMsg` and use a constructor like:

`var msg = new ClientGCMsgProtobuf<CMsgXYZ>( packetMsg );`

The direction of the message doesn't really matter. You can review the DotaMatchRequest sample for more details:
https://github.com/SteamRE/SteamKit/blob/master/Samples/10.DotaMatchRequest/DotaClient.cs

**Comment by azuisleet** [comment]
You should have enough information to get started. If you have any other questions, feel free to open a new issue.
