### ISSUE TITLE
Authorization in the Steam Client Desktop

### ISSUE THREAD

**Issue by Highlandernt** [SteamRE/SteamKit#811]
English is not my native language; please excuse typing errors.

If you check "Remember password" Steam will save the authorization data in
Steam\config\config.vdf
Steam\config\loginusers.vdf
Can you create them?

**Comment by azuisleet** [comment]
SteamKit does not interoperate with the on-disk files used by the Steam Client. SteamKit does however support login keys and Steam Guard sentry files.

You can review the Samples folder to see how to use Steam Guard:
https://github.com/SteamRE/SteamKit/tree/master/Samples/5.SteamGuard

There isn't a sample for login keys, but you store and provide the login key instead of the password:
https://github.com/SteamRE/SteamKit/issues/387#issuecomment-297665140

**Comment by Highlandernt** [comment]
I found out that the "config.vdf" file contains a token for reconnecting.
"ConnectCache"
 {
   "26726c11"		"020000002172250fa875cc33605de04a0378f0e570020b054c0f0c30"
}
Still to learn how and what is encrypted there.

**Comment by azuisleet** [comment]
On-disk formats are out of scope for SteamKit. You will have to do your own reverse engineering for those formats. 

If you have a SteamKit related question, feel free to open a new issue.

**Comment by ceptoplex** [comment]
@Highlandernt Sorry to abuse this issue because I don't see any other way to ask - but did you ever manage to figure out what kind of encrypted/hashed contents the `ConnectCache` values represent?

**Comment by Lordfirespeed** [comment]
Being able to authenticate using a `config.vdf` file would be very helpful for using SteamKit from hosted runners.

**Comment by darknight1050** [comment]
For others interested in this I reverse engineered the `ConnectCache` format and it is a JWT token that is protected by `CryptProtectData` from `Crypt32.dll`. I have some code that can de/encrypt it on my repo [https://github.com/darknight1050/SteamJWT](https://github.com/darknight1050/SteamJWT).

**Comment by Lordfirespeed** [comment]
> protected by `CryptProtectData` from `Crypt32.dll`

@darknight1050 I wonder how it works on Linux ... 
I would have thought it would be necessary to `Unprotect` the JWT in order to recover (and use) the auth'n credential. 
But that can't be the case, as it's possible to authenticate as a steam user on a remote machine by installing the `config.vdf` file generated on a local machine. 
Even when `config.vdf` is generated by a Windows computer and installed on an Ubuntu computer, it works.

**Comment by darknight1050** [comment]
@Lordfirespeed When did you test this? From my research the connect cache is in appdata now (on windows).
There is a legacy option that puts it in `config.vdf`. 
They might have changed the protection/encryption between these two.

**Comment by Lordfirespeed** [comment]
Hmm, it was a few months ago. You could be right. 
That would be frustrating, because `steam-deploy` (and actually almost any Steam Developer automation requiring auth'n...) relies on `config.vdf` ([reference](https://github.com/game-ci/steam-deploy/blob/main/README.md))

**Comment by landaire** [comment]
If anyone's coming to this in 2026:

1. Windows: DPAPI as mentioned, uses the account name as entropy: https://github.com/landaire/steamroom/commit/2d2e271a97fb6ce1536cf367e3d576a8b0dfbbba
2. macOS/Linux: pass the username through a KDF (sha2 in this case) and decrypts with AES-ECB nopad: https://github.com/landaire/steamroom/commit/de30bba3e33768324799725580290943f69cea32

I did not test with a Linux VDF file to confirm, but the code looks the same.

And if you need a VDF parser you could probably trivially build a `vdf2json` utility on top of https://github.com/landaire/steamroom/blob/2d2e271a97fb6ce1536cf367e3d576a8b0dfbbba/crates/steamroom/src/types/kv_de.rs

**Comment by Lordfirespeed** [comment]
so to be clear, the `ConnectCache` value is just an obfuscated refresh token?

**Comment by landaire** [comment]
`ConnectCache` in `local.vdf` is an **encrypted** refresh token. `ConnectCache` in `config.vdf` has unknown meaning to me but is of a different format and seems to be unrelated to authentication.
