### ISSUE TITLE
Steamkit2 in unity?

### ISSUE THREAD

**Issue by JaySlex** [SteamRE/SteamKit#963]
I tried to import it in my unity project, and i geta bunch of error message. How did you guys imported in unity?

**Comment by oxters168** [comment]
I remember also getting many errors in Unity. The errors were of missing references. So I would google the thing that was missing and find what library it came from, then find a dotnet/csharp version of it to import into Unity. There were quite a number of libraries that I needed to import.

One of those libraries was protobuf. I remember it had an issue with reflection or something, but there was a workaround that required the use of il2cpp rather than mono when building. With il2cpp you could force certain classes or namespaces to be included in the build. This was necessary because protobuf would use those classes at runtime but in a way that the compiler didn't realize it would so it wouldn't include them unless explicitly stated.

I think there was another issue but I don't recall what exactly it was, I think it had something to do with the network classes that were used in steamkit were not available in Unity or something like that. If I remember correctly, I just took the dll that included the classes needed and put it in my Unity project.

I don't know how helpful that was, but hopefully you'll be able to move forward with your project. Good luck!

**Comment by JaySlex** [comment]
thanks! I know i got error cause there where ? after some variable, but yeah ill try

**Comment by oxters168** [comment]
What I did to fix issues with syntax was to build the project in Visual Studio first then bring the SteamKit dll into Unity. I remember needing to set the dotnet framework version to something compatible to Unity before building.
