### ISSUE TITLE
Implement IConvertible on GlobalID

### ISSUE THREAD

**Issue by xPaw** [SteamRE/SteamKit#99]
*(and possibly other types)*

This would allow neat insertions with Dapper.NET, as of right now it throws `Unable to cast object of type 'SteamKit2.GlobalID' to type 'System.IConvertible'.` and requires manual conversion to ulong/uint64.

**Comment by VoiDeD** [comment]
As--shortly--discussed on IRC, I don't think that implementing `IConvertible` makes sense on types that are generally not converted to types other than `ulong`.

It'd probably be better to use ulongs directly in your objecting mappings, and expose a non-mapped property that can convert the field to a `GlobalID`.

Or even better simply use them as opaque ulongs, since the components of a `GlobalID` generally aren't useful in all but specific instances. This is even better supported by the availability of implicit conversions between `ulong` and `GlobalID` so that you can use either in any API that needs or exposes one.
